[workspace]

members = [
    "hangman_lib",
    "hangman_cli",
    "hangman_server",
]

[profile.dev]
opt-level = 1
# otherwise it takes about a second to process the data at first

[profile.release]
opt-level = 3
lto = true
debug = true
codegen-units = 1
# panic = "abort"
