[package]
name = "hangman_lib"
version = "0.1.0"
authors = ["Devon Burnham <novedevo@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
csv = "1"
regex = "1"
serde = "1"
bincode = "1"
rustc-hash = "1"
